spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/transaction_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        package-to-scan: com.marcosDev.transactionApi.entities
        format_sql: true
        dialect: org.hibernate.dialect.PostgresSQLDialect
  cloud:
    loadbalancer:
      ribbon:
        enable: true

server:
  port: 8080

